# Base Image
FROM node:20-alpine
WORKDIR /usr/src/app

# Dependency Installation 
COPY package*.json ./
RUN npm install

# Application Setup
COPY . .
RUN npx prisma generate

# Startup Configuration
EXPOSE 3000
CMD ["node", "index.js"]